
pipeline:
  build:
    image: maven:3.5-jdk-8
    pull: true
#    ADD: ./_data/nexus/settings.xml:/root/.m2/settings.xml
    commands:
      - mvn clean
      - -c
      - |
      - cp /drone/src/192.168.0.228/sven/JDBC-DAO/_data/nexus/settings.xml /root/.m2/settings.xml
      - mvn install